[package]
name = "rust_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
api42 = { git = "https://github.com/Alexdelia/api42.rs" }
reqwest = "0.11"
flutter_rust_bridge = "=2.0.0-dev.22"
